### ISSUE TITLE
Handling duplicates

### ISSUE THREAD

**Issue by stvdo** [i2group/notebook-sdk#11]
Good afternoon,

I am playing around with the duplicates from connectors in i2 Notebook. In my opinion, a very useful and important functionality!

On the chart the entities are merged/combined as expected. However in the list view the entities are not merged. I would also expect the merged entity here, perhaps with a 'show all merged entities' or 'show all original entities' (radio)button.

I am using i2 Analyze version 4.4.3 and i2 containers version 2.8.0

![image](https://github.com/i2group/notebook-sdk/assets/52672945/3d82278e-4f15-49cc-a529-1459dd2c1a44)

**Comment by Tim-Mawson-i2** [comment]
Hi @sdorresteijn88, I believe what you're seeing here is _uniting_, rather than _merging_. Matching _entity records_ have been united together into a single _node element_ - which is the element you see on the chart. Most often an element contains a single record, but here multiple Gene records have been united into a single element. The Lists tool list all the _records_ on the chart, rather than elements, which is why you're seeing all the Gene records. Note i2 Notebook doesn't yet support merging of records, more features around matching, uniting and merging are planned.

Hope this helps.
Tim

**Comment by stvdo** [comment]
Hi @Tim-Mawson-i2 good to hear that more features are planned. Looking forward to the upcoming releases:)
