### ISSUE TITLE
Plugin not loading in local running environment

### ISSUE THREAD

**Issue by stvdo** [i2group/notebook-sdk#4]
Good morning,

I created a React plugin, https://i2group.github.io/notebook-sdk/guide/tutorials/react-plugin.html. I worked perfect with the proxy on http://localhost:4000/opal/.

I added the 'script-src': 'unsafe-inline' to the plugin.json and ran 'npm run build'. After this I added the output to my config and redeployed it (Docker setup). But the plugin (button) doesn't appear. 

Can you see what I do wrong, or which step I missed?

My entrypoint.js
// @ts-check
/* global notebook */
/// <reference types="@i2analyze/notebook-sdk" />

/**
 * @param {import("@i2analyze/notebook-sdk").data.IReadOnlyCollection<import("@i2analyze/notebook-sdk").records.IChartRecord>} records
 */
function findGeospatialValue(records) {
  for (const record of records) {
    for (const propertyType of record.itemType.propertyTypes) {
      if (propertyType.logicalType === "geospatial") {
        const property = record.getProperty(propertyType);
        if (property !== undefined && !record.isValueUnfetched(property)) {
          return /** @type {import("@i2analyze/notebook-sdk").data.IGeoPoint} */ (
            property
          );
        }
      }
    }
  }
  return undefined;
}

async function main() {
  const api = await notebook.getEntryPointApi("13225b66-a546-4900-9a04-0f36c3dd17ad", "1.1");
  api.logger.info("plug-in running");

  const toolView = api.createToolView("React Leaflet Plugin", "./");
  const toggle = api.commands.createToolViewToggleCommand(
    {
      id: "00000000-0000-0000-0000-000000000007",
      name: "React Leaflet",
      icon: {
        type: "inlineSvg",
        svg: '<svg viewBox="0 0 24 24" fill="none"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <path d="M12 6H12.01M9 20L3 17V4L5 5M9 20L15 17M9 20V14M15 17L21 20V7L19 6M15 17V14M15 6.2C15 7.96731 13.5 9.4 12 11C10.5 9.4 9 7.96731 9 6.2C9 4.43269 10.3431 3 12 3C13.6569 3 15 4.43269 15 6.2Z" stroke="#000000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path> </g></svg>',
      },
      keyboardHelp: {
        category: "discover",
        label: "Toggle record inspector plug-in",
        keys: ["shift+r"],
      },
    },
    toolView
  );
  api.commands.applicationRibbon.homeTab.after(api.commands.applicationRibbon.homeTab.systemGroups.searchInfoStore).surfaceCommands(toggle);

  api.initializationComplete();
}

void main();

![image](https://github.com/i2group/notebook-sdk/assets/52672945/97ac6219-4db7-4aee-b63c-5ccaa7e35094)
![image](https://github.com/i2group/notebook-sdk/assets/52672945/dbba84ef-e330-4160-adb9-d715ecae9d25)
![image](https://github.com/i2group/notebook-sdk/assets/52672945/6d0337a5-1104-4e73-b2cc-a2db257b80e4)

**Comment by Tim-Mawson-i2** [comment]
Hi sdorresteijn88, 

Given you mentioned that it's all working with the devproxy, it's likely that it's the deployment that's causing issues. First, can you confirm that you plugin isn't being loaded at all (you should see something like `"Your plugin name" Loading plug-in (<you plugin guid>)` in the browser devtools console when opening i2 Notebook).

If the plugin isn't loading, then it might be that you've copied the whole plugin source folder to the `i2a-plugins/react-leaflet` folder, rather than the _built_ code that's in the `build` folder of your plugin (`build` contains the output of the `npm run build` command) - meaning the deployment can't _see_ your plugin. Try emptying `i2s-plugins/react-leaflet` and then copying everything inside your original `react-leaflet/build` to `i2a-plugins/react-leaflet`.

Tim

**Comment by stvdo** [comment]
Hi Tim,

Thanks a lot, the problem was indeed that I copied everything instead of only the build folder:(

**Comment by Anthony-Johnson-i2** [comment]
Thanks for the swift response @Tim-Mawson-i2. 

Closing as solved.
